version: 2
jobs:
  test:
    docker:
      - image: adambene/circleci-openjdk-awscli
    working_directory: ~/bootcamp-circle-cloudformation
    steps:
      - checkout
      - run: sbt test

  deploy:
    docker:
      - image: adambene/circleci-openjdk-awscli
    working_directory: ~/bootcamp-circle-cloudformation
    steps:
      - checkout
      - run: ./build-and-deploy-to-aws.sh ben-asg-InstanceProfile-Z2U47T146DP5 ben
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
              branches:
                only:
                  - master
          requires:
            - test